### ISSUE TITLE
Add upgrade 15 banner to dapp-inter

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter-jumper#23]
Enable banner on dapp-inter-jumper to notify users of service disruption because of Upgrade 15 chain upgrade.

'A chain upgrade (Proposal 74 - Agoric Upgrade 15) is planned to take place on Monday 2024-05-13 between 10:00am - 10:15am PST. Note this upgrade is only expected to take ~5mins but the UI will not be functional during this time'

**Comment by samsiegart** [comment]
Done (but changed "PST" to "PDT")
