### ISSUE TITLE
app.inter.trade redirects to non-mainnet UI hash with testnet selector (no way for user to select mainnet)

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter-jumper#24]
The EC voted in a new dapp-inter UI hash yesterday that looks to be problematic as it doesnt' include an option to select mainnet network. Normally dapp-inter updates default to mainnet and do not include the chain selector so this looks to be the incorrect IPFS hash from a different dapp-inter update

The voted in UI hash was bafybeiaijcvsa3aen7dguwugnkitysqrpquuiczibdav47mjfzh5zwafqy

**Comment by samsiegart** [comment]
They voted in a dev build which is not intended to be used with mainnet according to current requirements. The proposed mitigation for this type of mistake would violate these requirements, so I'm going to close this.
